TestClass::Construction
TestClass::Destruction
Caught exception: test_exception
